import "./globals.css";


// font family
const fontFamily = "--font-geist-sans";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Rayhan | Full-Stack Developer at FlexshipIT",
    template: "%s | Rayhan Portfolio"
  },
  description: "Full-Stack Developer at FlexshipIT specializing in Next.js, React, MongoDB, and Real-time systems with Socket.io. Explore my work on Land Office Automation, FairBazar, and ChatNest.",
  keywords: [
    "Rayhan Full-Stack Developer",
    "FlexshipIT Developer",
    "Next.js Expert Bangladesh",
    "MERN Stack Developer Gopalganj",
    "Socket.io Real-time Apps",
    "GSAP & Framer Motion Animations",
    "Gatsby Static Site Developer",
    "Software Engineer Portfolio"
  ],
  authors: [{ name: "Rayhan", url: "https://rayhan309.vercel.app" }],
  creator: "Rayhan",
  metadataBase: new URL("https://rayhan309.vercel.app"), // Replace with your actual domain
  openGraph: {
    title: "Rayhan | Full-Stack Engineer & Creative Developer",
    description: "Specializing in high-performance web applications, Real-time Socket.io systems, and premium UI animations at FlexshipIT.",
    url: "https://rayhan309.vercel.app",
    siteName: "Rayhan Portfolio",
    images: [
      {
        url: "/logo.png", // Recommended: 1200x630 pixel image
        width: 1200,
        height: 630,
        alt: "Rayhan - Full-Stack Developer Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Rayhan | Full-Stack Developer @ FlexshipIT",
    description: "Building scalable web solutions with Next.js, Socket.io, and GSAP. Check out my latest projects.",
    images: ["/logo.png"],
    creator: "@rayhan309", // Change to your actual Twitter handle
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: "your-google-verification-code", // Google Search Console code
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontFamily} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
