import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Rayhan | Full-Stack Developer Portfolio",
    template: "%s | Rayhan Portfolio"
  },
  description: "Full-Stack Developer specializing in React, Next.js, and Node.js. Check out my projects like ChatNest, Land Office Automation, and Xorit Academy.",
  keywords: ["Full-Stack Developer", "Next.js Developer", "Software Engineer", "MERN Stack", "Cyber Security", "AI/ML Learning Platform"],
  authors: [{ name: "Rayhan" }],
  creator: "Rayhan",
  openGraph: {
    title: "Rayhan | Full-Stack Developer Portfolio",
    description: "Building modern web applications with Next.js and Node.js.",
    url: "https://rayhan.vercel.app",
    siteName: "Rayhan Portfolio",
    images: [
      {
        url: "/logo.png", // আপনার একটি ভালো ছবির লিঙ্ক এখানে দিন
        width: 1200,
        height: 630,
        alt: "Rayhan Portfolio Preview",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Rayhan | Full-Stack Developer",
    description: "Expertise in React, Next.js, and Web Automation.",
    images: ["/logo.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
